import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

import { initializeApp } from "firebase/app";
import { getFirestore, collection, addDoc } from "firebase/firestore";
import firebaseConfig from "./firebase-applet-config.json";

dotenv.config();

// Initialize Firebase
const firebaseApp = initializeApp(firebaseConfig);
const db = getFirestore(firebaseApp, firebaseConfig.firestoreDatabaseId);

const app = express();
const PORT = parseInt(process.env.PORT || "3000", 10);

app.use(express.json());

// Lazy load Gemini Client to prevent crashing if GEMINI_API_KEY is missing at startup
let aiClient: GoogleGenAI | null = null;

function getAiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is not configured.");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// AI Tools Route
app.post("/api/ai-tool", async (req, res): Promise<any> => {
  const { tool, inputs } = req.body;

  if (!tool || !inputs) {
    return res.status(400).json({ error: "Missing 'tool' or 'inputs' parameters." });
  }

  try {
    const ai = getAiClient();
    let prompt = "";
    let systemInstruction = "Bạn là một Chuyên gia Cố vấn Giáo dục Quốc tế, Trưởng bộ phận Đời sống Học sinh (Student Life Director), và Cố vấn Nghiên cứu Ngôn ngữ học Ứng dụng xuất sắc. Bạn TRẢ LỜI HOÀN TOÀN BẰNG TIẾNG VIỆT trôi chảy, chuyên nghiệp và nhân văn.";

    switch (tool) {
      case "conflict-advisor":
        systemInstruction += " Bạn chuyên về kỷ luật tích cực, công lý phục hồi trong trường học quốc tế, và chăm sóc sức khỏe tâm lý của học sinh. Viết phản hồi có cấu trúc rõ ràng: 1. Các câu hỏi đối thoại phục hồi cần hỏi các bên. 2. Chiến lược kỷ luật tích cực phù hợp nhất. 3. Các bước hành động thực tiễn kế tiếp. Giữ giọng điệu thấu hiểu, mang tính giáo dục sâu sắc và chuẩn mực chuyên môn quốc tế.";
        prompt = `Hãy phân tích sự việc hành vi của học sinh trường quốc tế sau đây và phác thảo giải pháp can thiệp kỷ luật tích cực chi tiết bằng Tiếng Việt:
- Cấp học của học sinh: ${inputs.grade || "Trung học"}
- Mức độ nghiêm trọng: ${inputs.severity || "Nhẹ"}
- Chi tiết hành vi/sự việc mâu thuẫn: "${inputs.incidentDescription}"`;
        break;

      case "lesson-planner":
        systemInstruction += " Bạn chuyên về lĩnh vực Ngôn ngữ học Ứng dụng, xây dựng giàn giáo (scaffolding) ngôn ngữ ESL và giảng dạy dựa trên nhiệm vụ giao tiếp thực tế (Task-Based Learning). Viết dàn ý giáo án học tập toàn diện bằng Tiếng Việt bao gồm: 1. Thuyết Ngôn ngữ học Ứng dụng được áp dụng (ví dụ: Giả thuyết đầu vào của Krashen, Đầu ra của Swain, hoặc Phương pháp Nhận thức Xã hội). 2. Các Mục tiêu Bài học chính yếu (Objectives). 3. Các Hoạt động Tương tác cụ thể theo từng bước. 4. Chiến lược Đánh giá năng lực của học sinh.";
        prompt = `Thiết kế một giáo án học tập (Lesson Plan) hiện đại áp dụng lý thuyết Ngôn ngữ học ứng dụng chi tiết bằng Tiếng Việt:
- Đề tài bài học: ${inputs.topic}
- Trình độ ngôn ngữ của học sinh: ${inputs.studentLevel}
- Thời lượng tiết học: ${inputs.duration || "45 phút"}
- Trọng tâm ngôn ngữ/lý thuyết (ví dụ: Ngữ dụng học, Cú pháp, Thuyết SLA): ${inputs.linguisticFocus || "Năng lực giao tiếp thực tế"}`;
        break;

      case "report-drafter":
        systemInstruction += " Bạn chuyên về soạn thảo nhận xét học cơ cấu, tiến trình hành vi bổ trợ định hướng phục hồi. Hãy biên dịch từ các ý tóm tắt của người dùng thành các đoạn văn nhận xét bằng Tiếng Việt cực kỳ chuẩn mực, tế nhị, nhân văn nhưng khách quan thích hợp cho phụ huynh trường quốc tế đọc. Không dùng ngôn từ khô khan rập khuôn hay tiêu cực.";
        prompt = `Hãy soạn thảo đoạn nhận xét hành vi & học tập của học sinh bằng Tiếng Việt:
- Tên học sinh: ${inputs.studentName || "Học sinh"}
- Giọng điệu chủ đạo: ${inputs.tone || "Đồng cảm, nâng đỡ và định hướng phục hồi"}
- Các thế mạnh cốt lõi ghi nhận được: "${inputs.strengths}"
- Các khía cạnh cần thêm nỗ lực hoàn thiện: "${inputs.growthAreas}"`;
        break;

      default:
        return res.status(400).json({ error: `Unknown tool: ${tool}` });
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    const outputText = response.text || "No response generated by the AI model.";
    return res.json({ result: outputText });

  } catch (error: any) {
    console.error("Gemini API Error in backend:", error);
    return res.status(500).json({
      error: error.message || "Failed to process the AI request. Please check your GEMINI_API_KEY configuration.",
    });
  }
});

// Mock Database / Content Endpoint for Blog & Resources to show we build real feature-rich content
const blogPosts = [
  {
    id: "post-1",
    title: "Restorative Justice in the International Classroom",
    category: "Positive Discipline",
    date: "June 2026",
    readTime: "5 min read",
    summary: "How student supervisors can build mutual trust and reduce repetitive behavior and conflicts using circles and supportive feedback loops instead of old-school punitive measures.",
    content: `### Restorative Justice in the International Classroom

In high-pressure, multicultural international school environments, traditional punitive methods often fall short of addressing the underlying communication disconnects. When a student steps out of bounds, punitive detention might keep them out of class, but it rarely teaches communication skills.

#### The Restorative Framework
Instead of asking **"What rule was broken and who did it?"**, we shift our focus to:
1. **What happened, and what were people thinking at the time?**
2. **Who has been affected, and in what way?**
3. **What is needed to make things right?**

#### Implementation in Daily Operations
When handling disputes at the high school or middle school levels, I utilize a mini-conference structure. This invites students to sit together, declare their perspectives safely, and sign a mutual growth agreement. We emphasize **positive discipline** and **peer mediation**, empowering students to co-author their behavioral corrections.`,
  },
  {
    id: "post-2",
    title: "Second Language Acquisition (SLA) in Student Well-being",
    category: "Applied Linguistics",
    date: "May 2026",
    readTime: "7 min read",
    summary: "Analyzing how a student's linguistic background affects their peer interactions, confidence levels, and systemic inclusion in multicultural boarding or day schools.",
    content: `### SLA in Student Well-being

For international school students, learning does not just happen in a vacuum. Under Krashen's **Affective Filter Hypothesis**, high anxiety, low self-esteem, and school stress raise a cognitive barrier that prevents input from reaching the language acquisition center.

#### The Student life Connection
As a Student Life Officer, I see first-hand how language issues feed behavioral outbursts or classroom withdrawal.
- **Systemic Language Barriers**: If a student feels their communicative competence in English is doubted, they withdraw to monolingual peer circles, worsening social divides.
- **Sociocognitive Scaffolding**: By integrating collaborative, low-stakes activities in student lounges (like board games, student radio, or peer-led leadership councils), we lower the affective filter, boosting language fluency and emotional belonging simultaneously.`,
  },
  {
    id: "post-3",
    title: "Drafting Empathetic School Reports: A Practical Framework",
    category: "Educational Leadership",
    date: "April 2026",
    readTime: "4 min read",
    summary: "Strategies for communicating difficult behavioral or attendance feedback to parents in a positive, collaborative, and evidence-guided layout.",
    content: `### Drafting Empathetic School Reports

Reporting to parents is one of the most powerful pivot points in student mentoring. An aggressive tone triggers a defensive stance, whereas passive feedback fails to spark change.

#### The Sandwich Method with a Growth Twist
Constructive reporting uses our three-step pedagogical balance:
1. **The Foundation of Appreciation**: Explicitly state where the student excels socially or academically.
2. **The Restoration Pointer**: Outline the specific growth gap objectively (e.g., 'requires prompt arrival to first period' instead of 'continues to be lazy and late').
3. **Collaborative Invitation**: Offer a specific positive intervention plan that invites the parents and secondary advisors to support the student's development.`,
  },
];

const downloadableResources = [
  {
    id: "res-1",
    title: "Restorative Conference Guide & Worksheet",
    type: "PDF Template",
    size: "1.2 MB",
    downloads: "420+",
    description: "Step-by-step circular conversation scripts and template contract for managing secondary student behavioral negotiations.",
  },
  {
    id: "res-2",
    title: "Positive Classroom Integration Protocol",
    type: "DOCX Tool",
    size: "820 KB",
    downloads: "210+",
    description: "Comprehensive behavior matrix matching minor and severe infractions with constructive pedagogical learning responses.",
  },
  {
    id: "res-3",
    title: "Applied Linguistics SLA Lounge Assessment",
    type: "XLSX Form",
    size: "640 KB",
    downloads: "150+",
    description: "Observation check-sheets to analyze how peer groups form and chat in free time to assess real-world communicative confidence.",
  },
];

app.get("/api/blog", (req, res) => {
  res.json(blogPosts);
});

app.get("/api/resources", (req, res) => {
  res.json(downloadableResources);
});

app.post("/api/contact", async (req, res): Promise<any> => {
  const { name, email, message } = req.body;
  
  if (!name || !email || !message) {
    return res.status(400).json({ error: "Missing required fields." });
  }

  try {
    await addDoc(collection(db, "contactMessages"), {
      name,
      email,
      subject: "Liên hệ từ Portfolio Active Theory",
      message,
      createdAt: new Date()
    });
    return res.json({ success: true });
  } catch (error: any) {
    console.error("Firebase Error in server.ts:", error);
    return res.status(500).json({ error: error.message || "Failed to save message." });
  }
});

// Vite Middleware Routing Setup
const isProd = process.env.NODE_ENV === "production";

async function configureFrontend() {
  if (!isProd) {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }
}

configureFrontend().then(() => {
  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running in ${isProd ? "production" : "development"} mode on port ${PORT}`);
  });
});
